# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.29.5/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.29.5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/naim/Library/CloudStorage/OneDrive-UGent/DCL Spare Batch/DCL_ProBSP"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/naim/Library/CloudStorage/OneDrive-UGent/DCL Spare Batch/DCL_ProBSP"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.29.5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.29.5/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.29.5/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.29.5/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.29.5/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.29.5/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.29.5/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/naim/Library/CloudStorage/OneDrive-UGent/DCL Spare Batch/DCL_ProBSP/CMakeFiles" "/Users/naim/Library/CloudStorage/OneDrive-UGent/DCL Spare Batch/DCL_ProBSP//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/naim/Library/CloudStorage/OneDrive-UGent/DCL Spare Batch/DCL_ProBSP/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P "/Users/naim/Library/CloudStorage/OneDrive-UGent/DCL Spare Batch/DCL_ProBSP/CMakeFiles/VerifyGlobs.cmake"
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DP_Core

# Build rule for target.
DP_Core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DP_Core
.PHONY : DP_Core

# fast build rule for target.
DP_Core/fast:
	$(MAKE) $(MAKESILENT) -f src/lib/core/CMakeFiles/DP_Core.dir/build.make src/lib/core/CMakeFiles/DP_Core.dir/build
.PHONY : DP_Core/fast

#=============================================================================
# Target rules for targets named DP_Models

# Build rule for target.
DP_Models: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DP_Models
.PHONY : DP_Models

# fast build rule for target.
DP_Models/fast:
	$(MAKE) $(MAKESILENT) -f src/lib/models/CMakeFiles/DP_Models.dir/build.make src/lib/models/CMakeFiles/DP_Models.dir/build
.PHONY : DP_Models/fast

#=============================================================================
# Target rules for targets named DP_NN

# Build rule for target.
DP_NN: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DP_NN
.PHONY : DP_NN

# fast build rule for target.
DP_NN/fast:
	$(MAKE) $(MAKESILENT) -f src/lib/nn/CMakeFiles/DP_NN.dir/build.make src/lib/nn/CMakeFiles/DP_NN.dir/build
.PHONY : DP_NN/fast

#=============================================================================
# Target rules for targets named DP_Utilities

# Build rule for target.
DP_Utilities: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DP_Utilities
.PHONY : DP_Utilities

# fast build rule for target.
DP_Utilities/fast:
	$(MAKE) $(MAKESILENT) -f src/lib/utilities/CMakeFiles/DP_Utilities.dir/build.make src/lib/utilities/CMakeFiles/DP_Utilities.dir/build
.PHONY : DP_Utilities/fast

#=============================================================================
# Target rules for targets named DP_DynaPlex

# Build rule for target.
DP_DynaPlex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DP_DynaPlex
.PHONY : DP_DynaPlex

# fast build rule for target.
DP_DynaPlex/fast:
	$(MAKE) $(MAKESILENT) -f src/lib/dp/CMakeFiles/DP_DynaPlex.dir/build.make src/lib/dp/CMakeFiles/DP_DynaPlex.dir/build
.PHONY : DP_DynaPlex/fast

#=============================================================================
# Target rules for targets named DP_Algorithms

# Build rule for target.
DP_Algorithms: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DP_Algorithms
.PHONY : DP_Algorithms

# fast build rule for target.
DP_Algorithms/fast:
	$(MAKE) $(MAKESILENT) -f src/lib/algorithms/CMakeFiles/DP_Algorithms.dir/build.make src/lib/algorithms/CMakeFiles/DP_Algorithms.dir/build
.PHONY : DP_Algorithms/fast

#=============================================================================
# Target rules for targets named memory_checks

# Build rule for target.
memory_checks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 memory_checks
.PHONY : memory_checks

# fast build rule for target.
memory_checks/fast:
	$(MAKE) $(MAKESILENT) -f src/executables/memory_checks/CMakeFiles/memory_checks.dir/build.make src/executables/memory_checks/CMakeFiles/memory_checks.dir/build
.PHONY : memory_checks/fast

#=============================================================================
# Target rules for targets named executable_example

# Build rule for target.
executable_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 executable_example
.PHONY : executable_example

# fast build rule for target.
executable_example/fast:
	$(MAKE) $(MAKESILENT) -f src/executables/executable_example/CMakeFiles/executable_example.dir/build.make src/executables/executable_example/CMakeFiles/executable_example.dir/build
.PHONY : executable_example/fast

#=============================================================================
# Target rules for targets named exe_spare_parts

# Build rule for target.
exe_spare_parts: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exe_spare_parts
.PHONY : exe_spare_parts

# fast build rule for target.
exe_spare_parts/fast:
	$(MAKE) $(MAKESILENT) -f src/executables/exe_spare_parts/CMakeFiles/exe_spare_parts.dir/build.make src/executables/exe_spare_parts/CMakeFiles/exe_spare_parts.dir/build
.PHONY : exe_spare_parts/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... DP_Algorithms"
	@echo "... DP_Core"
	@echo "... DP_DynaPlex"
	@echo "... DP_Models"
	@echo "... DP_NN"
	@echo "... DP_Utilities"
	@echo "... exe_spare_parts"
	@echo "... executable_example"
	@echo "... memory_checks"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P "/Users/naim/Library/CloudStorage/OneDrive-UGent/DCL Spare Batch/DCL_ProBSP/CMakeFiles/VerifyGlobs.cmake"
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

